### ISSUE TITLE
Can the image `vijos/vj4` be pushed to Docker Hub?

### ISSUE THREAD

**Issue by moesoha** [vijos/vj4-docker#1]

**Comment by iceboy233** [comment]
Why not?

**Comment by moesoha** [comment]
Request the access to push `vijos/vj4` to Docker Hub.

@iceb0y

**Comment by iceboy233** [comment]
Created https://cloud.docker.com/u/vijos/repository/docker/vijos/vj4. Do you have a docker cloud account?

**Comment by moesoha** [comment]
It's `moesoha`, same as GitHub.

**Comment by iceboy233** [comment]
added as owner of `vijos` org on docker cloud

**Comment by moesoha** [comment]
@iceb0y thx.
