### ISSUE TITLE
Server response 500 ERROR

### ISSUE THREAD

**Issue by yinlinghunjiang** [vijos/vj4-docker#13]
I use docker to pull images 
it's all rights in pulling,but when i access https://mywebsite:8888
server response 500 error
how can i solve it?
![1](https://user-images.githubusercontent.com/68178871/129895131-75c4fb93-62e6-4a54-a71d-0b8858c65432.png)
`git clone git://github.com/vijos/vj4-docker.git

Cloning into 'vj4-docker'...

remote: Enumerating objects: 98, done.

remote: Counting objects: 100% (9/9), done.

remote: Compressing objects: 100% (9/9), done.

remote: Total 98 (delta 3), reused 0 (delta 0), pack-reused 89

Receiving objects: 100% (98/98), 28.21 KiB | 0 bytes/s, done.

Resolving deltas: 100% (50/50), done.

[root@VM-0-14-centos ~]# cd vj4-docker

[root@VM-0-14-centos vj4-docker]# cp .env.example .env
[root@VM-0-14-centos vj4-docker]# docker-compose up -d

Creating network "vj4-docker_default" with the default driver

Pulling rabbitmq (rabbitmq:latest)...

latest: Pulling from library/rabbitmq

16ec32c2132b: Already exists

3adbc39b91c4: Pull complete

e8b69dd838f7: Pull complete

c9104876e567: Pull complete

048896cf9ed8: Pull complete

b6c0ddc66feb: Pull complete

0b73ecf3c545: Pull complete

e0797741356a: Pull complete

0cdd82cb58d7: Pull complete

Digest: sha256:c27d5915d1ddad12ac905c78f467c6280f4c807e87ec69c3298fa8a90b2d9a26

Status: Downloaded newer image for rabbitmq:latest

Pulling web (vijos/vj4:)...

latest: Pulling from vijos/vj4

df20fa9351a1: Pull complete

36b3adc4ff6f: Pull complete

98eb400f742f: Pull complete

31cc876ef68f: Pull complete

badfb14c62c0: Pull complete

80008f9fad11: Pull complete

963b4525d8d2: Pull complete

8ec7d019e717: Pull complete

61f2bbd4597d: Pull complete

Digest: sha256:e391eea74cc44e8e9d6a4397f868082531bef4f4ab99914293b1d019aa93af95

Status: Downloaded newer image for vijos/vj4:latest

Creating vj4-docker_rabbitmq_1 ... done

Creating vj4-docker_mongodb_1  ... done

Creating vj4-docker_web_1      ... done

[root@VM-0-14-centos vj4-docker]# docker ps -a

CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS         PORTS                 
                                NAMES

68b0706fdcc8   vijos/vj4              "python docker-entry…"   2 minutes ago   Up 2 minutes   0.0.0.0:8888->8888/tcp, :::8888-

>8888/tcp             vj4-docker_web_1

75a8db9891a6   mongo:latest           "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes   27017/tcp    

   vj4-docker_mongodb_1
b9fd9c41a10e   rabbitmq:latest        "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes   4369/tcp, 5671-5672/tcp, 15691-

15692/tcp, 25672/tcp   vj4-docker_rabbitmq_1
`

**Comment by moesoha** [comment]
You can check `docker-compose logs` for error logs to debug.

**Comment by azeng233** [comment]
我也是这个问题
