### ISSUE TITLE
Some problem when I install

### ISSUE THREAD

**Issue by Philogag** [vijos/vj4-docker#7]
# Problem
1. My submition of problem is always Waiting
2. When regist, click "Send Verification Email" cause 500 Error

# My configration
I set up the server all by default

## This is the part o my configration
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                NAMES
c33d8879f642        vijos/jd4           "/bin/sh -c 'bash -c…"   4 minutes ago       Up 7 seconds                                             vj4_judge_1
2f12278d0c13        vijos/vj4           "python3 docker-entr…"   20 minutes ago      Up 20 minutes       0.0.0.0:8888->8888/tcp               vj4_web_1
4a6813d4074a        rabbitmq:latest     "docker-entrypoint.s…"   24 minutes ago      Up 24 minutes       4369/tcp, 5671-5672/tcp, 25672/tcp   vj4_rabbitmq_1
58f8b1c40e26        mongo:latest        "docker-entrypoint.s…"   24 minutes ago      Up 24 minutes       27017/tcp                            vj4_mongodb_1

$ cat ./data/judge/config.yaml
server_url: http://127.0.0.1:8888/
uname: judger
password: 123456

**Comment by gfhfhoo** [comment]
You need edit `.env` file at `/vj4-docker/`(maybe it has been hidden),and add this at end of file.
```
VJ_SMTP_HOST=
VJ_SMTP_PORT=
VJ_SMTP_USER=
VJ_SMTP_PASSWORD=
VJ_SMTP_FROM=
```
This config need you to edit.

**Comment by brewagebear** [comment]
> You need edit `.env` file at `/vj4-docker/`(maybe it has been hidden),and add this at end of file.
> 
> ```
> VJ_SMTP_HOST=
> VJ_SMTP_PORT=
> VJ_SMTP_USER=
> VJ_SMTP_PASSWORD=
> VJ_SMTP_FROM=
> ```
> 
> This config need you to edit.

I add this but, dosen't run vijos my firefox just showed comment like that 'page doesn't read'

**Comment by Philogag** [comment]
I don't understand your problem but mine has been soloved by setting the `.env` file

**Comment by brewagebear** [comment]
> I don't understand your problem but mine has been soloved by setting the `.env` file

Are you edit default .env file (.env.example)?
Can i see your `.env` file?

**Comment by Philogag** [comment]
you need copy the `.env.example` into `.env`,
then edit the `.env` and add the config of smtp server,
then run `docker-compose up -d` at command line.

this is the end of my `.env` file
```
VJ_SMTP_HOST=smtpdm.aliyun.com
VJ_SMTP_USER=system@***.xyz
VJ_SMTP_PASSWORD=*********
VJ_MAIL_FROM=system@***.xyz
```

**Comment by Philogag** [comment]
Another problem you may meet is the code judgement.
The jd4 judge server relies on a sufficiently high version of the system core.
You'd better upgrade your linux core to 5+

**Comment by brewagebear** [comment]
Thanks! i will try that.
